gnieh/fs2-data

README.md
csv/generic/src/fs2/data/csv/generic/CsvName.scala
csv/generic/src/fs2/data/csv/generic/CsvValue.scala
csv/generic/src/fs2/data/csv/generic/DerivedCellDecoder.scala
csv/generic/src/fs2/data/csv/generic/semiauto.scala
csv/generic/test/src/fs2/data/csv/generic/CellDecoderTest.scala

* derives cell decoders for coproducts where each case is
* an `object` or 
* a `case object` or
* has an implicit `CellDecoder` instance
* allows changing the expected value in CSV for objects by using the `@CsvName` annotation
* derives cell decoders for unary product types (case classes with one field)
See tests for some examples.

Add generic derivation for cell decoders

---

README.md
build.sc
csv/generic/src/fs2/data/csv/generic/ExportMacros.scala
csv/generic/src/fs2/data/csv/generic/auto.scala
csv/generic/test/src/fs2/data/csv/generic/AutoDerivationTest.scala
csv/src/fs2/data/csv/CsvRowDecoder.scala
csv/src/fs2/data/csv/Exported.scala
csv/src/fs2/data/csv/RowDecoder.scala
csv/test/src/fs2/data/csv/CsvParserTest.scala
json/test/src/fs2/data/json/JsonParsertest.scala
xml/test/src/fs2/data/xml/EventParserTest.scala

Using the same technique as in pureconfig and circe. Once #10 is merged, support for cell decoders can be added as well.
Additionally, I added a small beautification to the file-based tests, relativizing the file paths to make the test output more readable.

Auto derivation for csv-generic

---

csv/generic/src/fs2/data/csv/generic/CsvName.scala
csv/generic/src/fs2/data/csv/generic/DerivedCsvRowDecoder.scala
csv/generic/src/fs2/data/csv/generic/MapShapedCsvRowDecoder.scala
csv/generic/test/src/fs2/data/csv/generic/CellDecoderTest.scala
csv/generic/test/src/fs2/data/csv/generic/CsvRowDecoderTest.scala

For cases where your header name in the CSV file differs from the field name in your case class. See test for an example.

Allow usage of CsvName to rename fields in CsvRowDecoder derivation

---

csv/generic/src/fs2/data/csv/generic/MapShapedCsvRowDecoder.scala
csv/generic/test/src/fs2/data/csv/generic/CsvRowDecoderTest.scala

`Option` has a special handling in the implicit derivation and this part lacked the check for field renames via `@CsvName`. This PR adds a test case covering this issue and fixes it.

Fix CsvName on Option types

---

README.md
build.sc
json/interpolators/src/fs2/data/json/interpolators/SelectorInterpolator.scala
json/interpolators/src/fs2/data/json/interpolators/package.scala

This is done in another module so that the core Json library only
depends on fs2, and doesn't bring extra dependencies to user who do not
want it.

Add Json selector interpolator

---

documentation/docs/json/index.md
json/src/fs2/data/json/internal/Renderer.scala
json/src/fs2/data/json/package.scala
json/src/fs2/data/json/tokens.scala
json/test/src/fs2/data/json/RenderSpec.scala
json/test/src/fs2/data/json/TokenizerSpec.scala

In order to make the full roundtrip, this adds:
- pretty/compact printing of Json streams
- tokenizing ASTs

Add more JSON utilities

---

csv/src/fs2/data/csv/CellDecoder.scala
csv/src/fs2/data/csv/CsvRowDecoder.scala
csv/src/fs2/data/csv/RowDecoder.scala
documentation/docs/csv/index.md

- Implement the common mapping operators directly on the decoder
classes, so that it is easier to discover in IDEs.
- Add a comment in decoder scaladoc about the cats import to get all
the operators.
- Add a `CellDecoder` code snippet in the documentation to desmonstrate
usage of `emap`.
- Unify all decoder operators.

Make CSV decoders more newcomer friendly

---

.travis.yml
csv/src/fs2/data/csv/internals/RowParser.scala
json/src/fs2/data/json/internal/TokenParser.scala
xml/src/fs2/data/xml/internals/EventParser.scala

Benchmarks show that a lot of time is spent creating and converting
`Chain`, which are use to accumulate the chunks. By using a
`VectorBuilder` we have a more appropriate structure for the
accumulator, which we can reuse for each chunk.

Use VectorBuilder as chunk accumulator

---

documentation/docs/json/index.md
json/src/fs2/data/json/JsonException.scala
json/src/fs2/data/json/SelectorParser.scala
json/src/fs2/data/json/internal/TokenSelector.scala
json/src/fs2/data/json/selectors.scala
json/test/src/fs2/data/json/JsonSelectorSpec.scala

This selector fails the stream if a selected field is not present in the
object the selector is applied to. It can be useful when you know your
data must contain the field and want to raise an error if not (e.g. to
detect typos).
fixes #30

Add mandatory field selector

---

documentation/docs/json/index.md
json/src/fs2/data/json/internal/TokenParser.scala
json/src/fs2/data/json/internal/TokenSelector.scala
json/src/fs2/data/json/internal/ValueParser.scala
json/src/fs2/data/json/internal/package.scala
json/test/src/fs2/data/json/JsonExceptionSpec.scala
xml/src/fs2/data/xml/internals/EventParser.scala
xml/src/fs2/data/xml/internals/package.scala
xml/test/src/fs2/data/xml/XmlExceptionSpec.scala

The idea is to have a stream that emits all valid values up to the first
exception. Discarding the currently accumulating chunk can result in
some data being sometimes emitted or not, depending on the chunk size.
Observable behavior of the stream should not depend on how data is
chunked, so all valid data _so far_ must always be emitted.

Ensure all values are emitted before raising

---

build.sc
scalafix/src/fs2/data/fix/v1/csv/EmitsRows.scala
scalafix/src/fs2/data/fix/v1/json/EmitsTokens.scala
scalafix/src/fs2/data/fix/v1/xml/EmitsEvents.scala

Goal of these rules is to provide as much automatic rewriting as possible to cope with source incompatibility in version 1.
Closes #32

Add Scalafix Rules

---

csv/src/fs2/data/csv/internals/RowParser.scala
csv/src/fs2/data/csv/package.scala
csv/test/src/fs2/data/csv/CsvParserTest.scala
documentation/docs/csv/index.md

We had a use case recently where we have an unquoted CSV to parse that contains values with quotation marks. An example might be:
```
name,age,description
John Doe,75,"Starts with Quotes" but ends without
```
The current parser assumes a field beginning with a quote is a quoted field, per RFC, but the data here doesn't reflect that and we need all quotes to be treated literally.
This PR allows for a parsing flag to treat quotes either RFC-compliant or literal.
Note: it probably could use a dedicated test. I wanted to put this up first to get some eyes on it, however.

Customize csv quote handling

---

documentation/docs/json/index.md
documentation/docs/json/libraries.md
json/src/fs2/data/json/internal/TokenSelector.scala
json/src/fs2/data/json/package.scala
json/src/fs2/data/json/selector/dsl.scala
json/test/src/fs2/data/json/JsonSelectorSpec.scala

One of them allows for filtering values out of the stream, which
includes to be cautious to be sure the emitted stream is still valid. We
have to make sure that the key was not emitted if the value is going to
be dropped. This introduces a way to delay the emission of a key until
we know for sure the value is kept.
Fixes #47

Add more Json transformation pipes

---

csv/generic/src/fs2/data/csv/generic/MapShapedCsvRowEncoder.scala
csv/src/fs2/data/csv/CsvRow.scala
csv/src/fs2/data/csv/internals/CsvRowParser.scala
csv/src/fs2/data/csv/package.scala
csv/test/src/fs2/data/csv/CsvParserTest.scala

When a header row is required by the user, then it is better to check
consistency of following rows, so that we do not emit bogus rows where
length of headers and values do not match. This can lead to hard to spot
and debug problems.
Fixes #51

Check consistency between row and header length

---

csv/src/fs2/data/csv/exceptions.scala
csv/src/fs2/data/csv/internals/CsvRowParser.scala

When raising header size mismatches, use this specific error.
It will cause, for example, exception reporting software like Sentry to
correlate these exceptions separately from logical errors like a bad Decoder
This should be backwards compatible since it's a subclass

Add HeaderSizeError for downstream consumers to match on

---

build.sbt
csv/generic/src/fs2/data/csv/generic/DerivedCellEncoder.scala
documentation/docs/json/index.md
documentation/docs/json/libraries.md
json/circe/src/fs2/data/json/circe/package.scala
json/src/fs2/data/json/ast/Tokenizer.scala
json/src/fs2/data/json/internal/ObjectWrapper.scala
json/src/fs2/data/json/package.scala

Add Json stream wrappers

---

json/shared/src/main/scala/fs2/data/json/JsonContext.scala
json/shared/src/main/scala/fs2/data/json/JsonException.scala
json/shared/src/main/scala/fs2/data/json/internal/TokenParser.scala
json/shared/src/main/scala/fs2/data/json/internal/TokenSelector.scala
json/shared/src/main/scala/fs2/data/json/selectors.scala
json/shared/src/test/scala/fs2/data/json/JsonSelectorSpec.scala

This PR intentionally restricts the context to filtering and transformation. It induces overhead which might degrade general parsing too much and even prevent from parsing deeply nested JSON values. Restricting to selectors is ok as the context will be as deep as the selector, independently of the JSON value.

Add JSON context in when using selectors

---

.gitignore
csv/shared/src/main/scala/fs2/data/csv/internals/CsvRowParser.scala
csv/shared/src/main/scala/fs2/data/csv/package.scala

The use case for this is code that wants to parse an unreliable file, discard
"bad" rows, but continue to preserve the "good" rows, rather than failing the
whole process

Add a csv 'attempt' variant to allow for by-row error handling

---

cbor/shared/src/main/scala/fs2/data/cbor/low/internal/ItemParser.scala

When a chunk is pulled, we need to recursively ensure that it is not
empty in a stack safe way.

Fix recursive chunk `uncons`

---

build.sbt
json/interpolators/src/main/scala/fs2/data/json/interpolators/package.scala

This version also fixes the problem with scala 2.13, which we can now
use as default scala version for documentation.

Switch to new contextual-core library

---

csv/shared/src/main/scala/fs2/data/csv/RowDecoderF.scala
csv/shared/src/main/scala/fs2/data/csv/RowEncoderF.scala
csv/shared/src/main/scala/fs2/data/csv/RowF.scala

Instances that come for free as their underlying collections are isomorphic to rows. Useful in combination with the new CSV pipes.

Add some convenience CSV coders

---

build.sbt
documentation/docs/json/interpolators.md
json/interpolators/src/main/scala/fs2/data/json/interpolators/SelectorInterpolator.scala
json/interpolators/src/main/scala/fs2/data/json/interpolators/package.scala
json/interpolators/src/test/scala/fs2/data/json/interpolators/JsonInterpolatorsTest.scala
json/shared/src/main/scala/fs2/data/json/SelectorParser.scala

As contextual isn't moving towards Scala 3 (yet), this PR replaces it with the smaller, more focused and perfectly cross-building typelevel/literally lib.
A modified extract from #150 to make this change before the next RC.

Replace contextual with literally

---

build.sbt

With the exclusion of the `text.js` module the site should build properly again (see https://github.com/sbt/sbt-unidoc/issues/21). And sbt 1.5.0 brought some deprecation warnings about syntax that are also fixed in this PR.
@satabin A RC2 after this one (then including the website update as the pipeline should no longer fail)?

Fix makeSite and sbt deprecation warnings

---

csv/shared/src/main/scala/fs2/data/csv/CsvRow.scala
csv/shared/src/test/scala/fs2/data/csv/CsvRowTest.scala

This new function adds the missing header in case it was not present in
the original row.
Due to potential problem implementing a correct behavior for index based
setting in case of rows with headers, this function is only added for
name based access.
A new function is added, not to break existing code with the former
behavior of ignoring missing headers.
This is the 0.x port of #217

Add a way to set a value that adds missing column

---

csv/shared/src/main/scala/fs2/data/csv/RowF.scala
csv/shared/src/test/scala/fs2/data/csv/RowFTest.scala

This new operators allows for adding a column if the row initially
didn't have the header. In this case the column is added to the end of
the row.

Make it possible to add a column by header name

---

build.sbt
documentation/docs/json/index.md
documentation/docs/json/libraries.md
documentation/docs/json/patches.md
json/circe/shared/src/main/scala/fs2/data/json/circe/package.scala
json/shared/src/main/scala/fs2/data/json/ast/package.scala
json/shared/src/main/scala/fs2/data/json/codec/Deserializer.scala
json/shared/src/main/scala/fs2/data/json/codec/Serializer.scala
json/shared/src/main/scala/fs2/data/json/codec/package.scala
json/shared/src/main/scala/fs2/data/json/internal/TokenSelector.scala
json/shared/src/main/scala/fs2/data/json/package.scala
json/shared/src/test/scala/fs2/data/json/JsonSelectorSpec.scala

In addition to parsing and transforming Json ASTs, this adds a way to
work with plain Scala value when the udnerlying Json library has some
concept of codecs.
This is also the oppportunity to rationalize the selector code a bit,
making the trasformation pipes more regular and generic.
Old `json` package level transform pipes are deprecated in favor of
their variant in the `ast` package. This allows for semantically scoped
transformation pipes.

Add support for codecs

---

build.sbt

Noticed we don't cross-build it though we can thanks to https://index.scala-lang.org/artifacts/satabin/fs2-data

Cross-build JSON interpolators module to scala.js

---

csv/shared/src/test/scala/fs2/data/csv/CsvParserTest.scala
documentation/docs/index.md
text/shared/src/main/scala/fs2/data/text/package.scala

Add `CharLikeChunks` instance for UTF-8 to ease use (for users it's not clear why they can get ISO-8859-1 & Co via import and not UTF-8). Its implementation is basically what users are currently expected to do themselves, just wrapped up for convenience.

Add CharLikeChunks for UTF-8

---

xml/src/main/scala/fs2/data/xml/XmlEvent.scala
xml/src/main/scala/fs2/data/xml/internals/EventParser.scala
xml/src/main/scala/fs2/data/xml/internals/MarkupToken.scala
xml/src/main/scala/fs2/data/xml/package.scala
xml/src/test/scala/fs2/data/xml/EventParserTest.scala
xml/src/test/scala/fs2/data/xml/XmlExceptionSpec.scala

Comments can be useful to keep when transforming XML from source to
source.

Make it possible to keep comments

---

xml/scala-xml/src/main/scala/fs2/data/xml/scalaXml/package.scala
xml/src/main/scala/fs2/data/xml/dom/DocumentBuilder.scala
xml/src/main/scala/fs2/data/xml/dom/TreeParser.scala
xml/src/main/scala/fs2/data/xml/internals/EventParser.scala
xml/src/test/scala/fs2/data/xml/EventParserTest.scala
xml/src/test/scala/fs2/data/xml/dom/EventifierSpec.scala

The specification allows for `misc` appearing after the root element,
and the event parser should support this, as well as the document
builder.
Since a stream can contain concatenated XML documents, a choice has to
be made regarding how misc is associated between 2 documents in the
stream. This implementation makes the choice to associate the misc as
postlog of the previous document since it allows to emit early without
knowing what comes next (i.e. whether the stream actually contains only
one document or several documents).

Allow for XML postlog

---

text/shared/src/main/scala/fs2/data/text/CharRanges.scala
xml/src/main/scala/fs2/data/xml/internals/EventParser.scala
xml/src/test/scala/fs2/data/xml/EventParserTest.scala

Previous version was based on an obsolete definition of what valid
characters can appear in names.
The new ones maps with the character ranges described in the latest
version of the specification.
Ranges are represented as a specialized minimal implementation of a
Discrete Interval Encoding Tree.
Fixes #337

Fix name parsing

---

xml/src/main/scala/fs2/data/xml/XmlEvent.scala
xml/src/main/scala/fs2/data/xml/package.scala
xml/src/test/scala/fs2/data/xml/XmlEventShowTest.scala
xml/src/test/scala/fs2/data/xml/XmlRenderTest.scala

Fix buggy Show instance for XmlEvent and provide a pipe to render events with collapsed empty tags.

Fix XML rendering

---

.github/workflows/release.yml

Hopefully fixes the problem we have with releasing.

Remove setup-gpg, refresh release workflow

---

csv/generic/shared/src/main/scala-2/fs2/data/csv/generic/internal/MapShapedCsvRowDecoder.scala
csv/generic/shared/src/main/scala-3/fs2/data/csv/generic/internal/OptCellDecoder.scala
csv/generic/shared/src/main/scala-3/fs2/data/csv/generic/semiauto.scala
csv/generic/shared/src/test/scala/fs2/data/csv/generic/CsvRowDecoderTest.scala
csv/generic/shared/src/test/scala/fs2/data/csv/generic/RowDecoderTest.scala

Was probably meant as an optimization, but there empty strings can be legitimate. Users can still require non-emptiness using a cell decoder or by parsing into Option.

Allow empty csv cell strings in generic derivation

---

csv/shared/src/main/scala/fs2/data/csv/RowF.scala
csv/shared/src/test/scala/fs2/data/csv/RowFTest.scala

Add a way to, when working with rows directly, deal comfortably with optional cell values. New methods on `RowF` added instead of automatically deriving `CellDecoder` instances for `Option` to not interfere with generic derivation of row decoders and to capture user intent better.

Add asNonEmpty and asNonEmptyAt

---

csv/shared/src/main/scala/fs2/data/csv/RowDecoderF.scala
csv/shared/src/test/scala/fs2/data/csv/RowDecoderFTest.scala

Allow to work more easily with CSVs that contain bad rows as you can lift the errors to value level more easily and handle them there afterwards.

CSV decoder Instances for DecoderResult

---

csv/generic/shared/src/main/scala-2/fs2/data/csv/generic/internal/DerivedCsvRowDecoder.scala
csv/generic/shared/src/main/scala-2/fs2/data/csv/generic/internal/DerivedCsvRowEncoder.scala
csv/generic/shared/src/main/scala-2/fs2/data/csv/generic/internal/MapShapedCsvRowDecoder.scala
csv/generic/shared/src/main/scala-2/fs2/data/csv/generic/internal/MapShapedCsvRowEncoder.scala

Turns out we don't have to track the type of the case class we're deriving for while deriving the corresponding HList codec. MiMa seems happy as the only changes are type parameters and I don't expect users to ever call the affected methods from their code, so it's source-compatible.

Clean up type params

---

csv/shared/src/main/scala/fs2/data/csv/ParseableHeader.scala
csv/shared/src/main/scala/fs2/data/csv/WriteableHeader.scala
documentation/docs/csv/index.md

Add helpers for the common case where you want to decode or encode headers one by one.

Make header type classes easier to use

---

build.sbt
finite-state/shared/src/main/scala/fs2/data/pfsa/Candidate.scala
finite-state/shared/src/main/scala/fs2/data/pfsa/PDFA.scala
finite-state/shared/src/main/scala/fs2/data/pfsa/Pred.scala
finite-state/shared/src/main/scala/fs2/data/pfsa/Regular.scala
finite-state/shared/src/test/scala/fs2/data/pfsa/RegularSpec.scala
finite-state/shared/src/test/scala/fs2/data/pfsa/package.scala

Based on regular expression derivation with character classes, generalized to predicates, this allows to have a generic direct DFA construction algorithm for any regular language.
This allows to share implementation between several query languages (XPath and JsonPath might also be rewritten to use this representation instead of computing the NFA first).
Implementation is based on the paper [_Regular-expression derivatives reexamined_](https://www.ccs.neu.edu/home/turon/re-deriv.pdf)

Add regular language implementation

---

build.sbt
finite-state/shared/src/main/scala/fs2/data/esp/ESP.scala
finite-state/shared/src/main/scala/fs2/data/esp/Expr.scala
finite-state/shared/src/main/scala/fs2/data/esp/Rhs.scala
finite-state/shared/src/main/scala/fs2/data/mft/MFT.scala
finite-state/shared/src/main/scala/fs2/data/mft/MFTBuilder.scala
finite-state/shared/src/main/scala/fs2/data/mft/Rules.scala
finite-state/shared/src/main/scala/fs2/data/mft/package.scala
finite-state/shared/src/main/scala/fs2/data/mft/query/Query.scala
finite-state/shared/src/main/scala/fs2/data/mft/query/QueryCompiler.scala
finite-state/shared/src/main/scala/fs2/data/pattern/Compiler.scala
finite-state/shared/src/main/scala/fs2/data/pattern/Selectable.scala
finite-state/shared/src/test/scala/fs2/data/MiniXML.scala
finite-state/shared/src/test/scala/fs2/data/MiniXPath.scala
finite-state/shared/src/test/scala/fs2/data/mft/QuerySpec.scala

The common query language over tree structures, based on the technique described in [_XQuery Streaming by Forest Transducers_](https://doi.org/10.1109/ICDE.2014.6816714).
This will be used to implement compilation of jq and xquery queries.

Add tree query compiler implementation

---

csv/generic/shared/src/main/scala-3/fs2/data/csv/generic/internal/OptCellDecoder.scala
csv/generic/shared/src/main/scala-3/fs2/data/csv/generic/semiauto.scala
csv/generic/shared/src/test/scala/fs2/data/csv/generic/CsvRowDecoderTest.scala
csv/shared/src/main/scala/fs2/data/csv/RowF.scala

@alycklama and I noticed in https://github.com/gnieh/fs2-data/pull/436 that certain built-in decoders have inconsistent behaviour between Scala 2 and 3.
Since this inconsistency is unrelated to our PR, we decided to make a separate issue to investigate this.
I think it is related to the Shapeless types used in the `MapShapedCsvRowDecoder`, since Shapeless makes heavy use of Macros which have changed in Scala 3. However, that is where my knowledge of Shapeless ends.
This PR adds a few unit tests that demonstrate the problem. They succeed on Scala 2 and fail on Scala 3.

Investigation in Scala2/Scala3 decoder inconsistency

---

csv/shared/src/main/scala/fs2/data/csv/CsvRow.scala
csv/shared/src/main/scala/fs2/data/csv/exceptions.scala
csv/shared/src/test/scala/fs2/data/csv/CsvParserTest.scala

Allows to handle broken CSV files where column count mismatches more precisely than when having to match the error message.

Use HeaderSizeError

---

.github/workflows/ci.yml
build.sbt
csv/shared/src/main/scala/fs2/data/csv/RowF.scala
csv/shared/src/test/scala/fs2/data/csv/RowFTest.scala
documentation/docs/csv/index.md
documentation/docs/json/index.md

An optional field might be encoded in various ways, depending on the CSV data emitter. `RowF` can handle most scenarios by providing a way to define:
- how to react when a field is not present in the dataset at all (i.e. the column is missing in the input data)
- what values are considered empty (e.g. empty string, or `null`, or `N/A`)

Generalize optional fields handling for `RowF`

---

csv/shared/src/main/scala/fs2/data/csv/internals/RowParser.scala
csv/shared/src/test/scala/fs2/data/csv/RowParserTest.scala

Increment the line counter when an empty line in CSV input is parsed (resulting in now row).
Closes #461

Fix CSV line numbers in presence of empty rows

---

cbor/shared/src/main/scala/fs2/data/cbor/CborException.scala
cbor/shared/src/main/scala/fs2/data/cbor/high/internal/ValueParser.scala
cbor/shared/src/main/scala/fs2/data/cbor/high/internal/ValueSerializer.scala
cbor/shared/src/test/scala/fs2/data/cbor/high/ValueParserTest.scala

Add support for bignum decoding to match the encoding logic for high-level integer values and hence enable roundtrip for them.
Closes #452

Decode bignums properly

---

cbor/shared/src/main/scala/fs2/data/cbor/high/internal/ValueSerializer.scala
cbor/shared/src/test/scala/fs2/data/cbor/RoundtripTest.scala

Serialisation of CBOR numbers missed byte padding for 32 and 64-bit wide numbers, so they were not encoded in the full length and destroyed the validity of the whole stream.

Fix CBOR number encoding

---

benchmarks/src/main/resources/twitter.json
benchmarks/src/main/scala/fs2/data/benchmarks/JsonParserBenchmarks.scala
benchmarks/src/main/scala/fs2/data/benchmarks/JsonValueBenchmarks.scala
build.sbt

The idea is to compare the JSON parser performances against two other ones:
- jawn
- circe-fs2
The former is purely indicative and fs2-data does not aim to compete with it, but the goal is to reach less than 2x slower than jawn and on par with crice-fs2.
With the current main, here are the results on my computer (openjdk 19, Nixos, Intel Core i5-6500, 24GiB RAM):
```
Benchmark                                    Mode  Cnt     Score     Error  Units
JsonParserBenchmarks.parseCirceFs2           avgt   10  5185.365 ±  22.193  us/op
JsonParserBenchmarks.parseJsonFs2DataTokens  avgt   10  4952.242 ±  26.871  us/op
JsonParserBenchmarks.parseJsonFs2DataValues  avgt   10  7431.730 ± 111.586  us/op
JsonParserBenchmarks.parseJsonJawn           avgt   10  1928.299 ±   8.318  us/op …
```

Add Json parser benchmarks

---

finite-state/shared/src/main/scala/fs2/data/mft/query/Query.scala
finite-state/shared/src/main/scala/fs2/data/mft/query/QueryCompiler.scala
finite-state/shared/src/main/scala/fs2/data/pfsa/PDFA.scala
finite-state/shared/src/main/scala/fs2/data/pfsa/PNFA.scala
finite-state/shared/src/main/scala/fs2/data/pfsa/Regular.scala
finite-state/shared/src/test/scala/fs2/data/mft/QuerySpec.scala
json/src/main/scala/fs2/data/json/jq/internal/ESPJqCompiler.scala
json/src/test/scala/fs2/data/json/jq/JqSpec.scala

In some query languages and for some formats, when a path is not found, it is fine to output nothing. For instance for XML, an empty sequence of nodes is ok.
However in some cases, a default value has to be output. This is the case in the JSON query language. When the query builds an object whose value is a sub-query, then the value cannot be empty, even if the sub-query finds no element. Moreover, the query must return exactly one result. If it return zero or more than one element, then the generated JSON data is invalid.
But in the JSON query lanuage, generating no data is still valid, and happens when the path is iterated over, for instance.
This change allows for the query to parameterize for each path whether it should return a (unique) default value, or not. If not, then the …

Add a default fallback value to paths

---

finite-state/shared/src/main/scala/fs2/data/esp/ESP.scala
finite-state/shared/src/main/scala/fs2/data/esp/Expr.scala
finite-state/shared/src/main/scala/fs2/data/esp/Rhs.scala
finite-state/shared/src/main/scala/fs2/data/mft/MFT.scala
finite-state/shared/src/main/scala/fs2/data/mft/package.scala
finite-state/shared/src/main/scala/fs2/data/mft/query/QueryCompiler.scala
json/src/main/scala/fs2/data/json/jq/internal/ESPCompiledJq.scala
json/src/main/scala/fs2/data/json/tagged/JsonTagger.scala
json/src/test/scala/fs2/data/json/jq/JqSpec.scala

Fixes the problem that the default is emitted in objects if the first field is not matching.
Now the default constructor is a first class citizen throughout the process. It is emitted only if it is not followed by a value constructor in the stream processor.

Fix default value

---

site/documentation/xml/index.md
site/documentation/xml/xpath.md
xml/src/main/scala/fs2/data/xml/Attr.scala
xml/src/main/scala/fs2/data/xml/internals/Renderer.scala
xml/src/main/scala/fs2/data/xml/package.scala
xml/src/test/scala/fs2/data/xml/XmlRenderTest.scala

Add support for pretty printing XML

---

build.sbt
examples/jqlike/src/main/scala/fs2/data/example/jqlike/JqLike.scala
json/src/main/scala/fs2/data/json/internal/Renderer.scala
json/src/main/scala/fs2/data/json/package.scala
json/src/main/scala/fs2/data/json/tokens.scala
json/src/test/scala/fs2/data/json/RenderSpec.scala
site/cookbooks/jq.md
site/documentation/json/index.md
text/shared/src/main/scala/fs2/data/text/render/DocEvent.scala
text/shared/src/main/scala/fs2/data/text/render/RenderException.scala
text/shared/src/main/scala/fs2/data/text/render/Renderable.scala
text/shared/src/main/scala/fs2/data/text/render/Renderer.scala
text/shared/src/main/scala/fs2/data/text/render/internal/Annotated.scala
text/shared/src/main/scala/fs2/data/text/render/internal/Position.scala
text/shared/src/main/scala/fs2/data/text/render/internal/StreamPrinter.scala
text/shared/src/main/scala/fs2/data/text/render/package.scala
xml/src/main/scala/fs2/data/xml/XmlEvent.scala
xml/src/main/scala/fs2/data/xml/package.scala
xml/src/test/scala/fs2/data/xml/XmlRenderTest.scala

It is inspired by the paper [_Lazy v. Yield: Incremental, Linear Pretty-printing_](https://okmij.org/ftp/continuations/PPYield/yield-pp.pdf) by Oleg Kiselyov, Simon Peyton-Jones, and Amr Sabry.
It adds indentation and alignment features to be useful in the context of streaming tree structure pretty printing (XML, JSON, ...).
Any type that has an instance of `Renderable` can be printed.
The printer guarantees that the data is printed as early as possible and the it is correct up to the first malformed tree structure.

Add streaming pretty printing utilities

---

.scala-steward.conf

Since this is a library, we stick to the LTS version.
Refers to #587

Pin scala 3 to 3.3.x branch

---

csv/shared/src/main/scala/fs2/data/csv/CellEncoder.scala
csv/shared/src/test/scala/fs2/data/csv/CellEncoderTest.scala

Add ability to build `CellEncoder` from `cats.Show`

---

csv/shared/src/main/scala/fs2/data/csv/package.scala
csv/shared/src/test/scala/fs2/data/csv/RowGeneratorTest.scala
site/documentation/csv/index.md

Fixes #621 
A new method is created and the old one is deprecated to keep binary compatibility.

Emit an error if row and header size mismatch

---

benchmarks/src/main/scala/fs2/data/benchmarks/PrinterBenchmarks.scala
build.sbt
json/src/main/scala/fs2/data/json/package.scala
text/shared/src/main/scala/fs2/data/text/render/internal/Annotated.scala
text/shared/src/main/scala/fs2/data/text/render/internal/NonEmptyIntList.scala
text/shared/src/main/scala/fs2/data/text/render/internal/StreamPrinter.scala

This change addresses #634 in two ways:
- A change to the generic pretty printer that allows to avoid:
- Boxing of integers when computing the layout
- Instantiating many tuples that are immediately discarded
- Creating intermediate chunks by fusing the annotation and rendering phases
- Re-introduce a direct compact rendering for JSON, that is way simpler than leveraging the generic printer with no groups
By doing so, the compact rendering should be back to the performance in 1.10 and the pretty case is improved a bit.
Here are some benchmark results with the compact rendering in 1.11.1 as the baseline. 1.11.2 represents the results with this change.
```mermaid
xychart-beta
title "Rendering of int array"
x-axis ["Pretty 1.10", "Pretty 1.11.1", "Pretty 1.11.2", "Compact 1.11.1", "Compact …
```

Improve stream rendering performances

---

finite-state/shared/src/main/scala/fs2/data/pfsa/TreeQueryPipe.scala
json/src/main/scala/fs2/data/json/jsonpath/package.scala
json/src/test/scala/fs2/data/json/jsonpath/JsonPathSpec.scala
site/documentation/json/jsonpath.md
site/documentation/xml/xpath.md
xml/src/main/scala/fs2/data/xml/xpath/package.scala
xml/src/test/scala/fs2/data/xml/xpath/QueryPipeSpec.scala

The documentation now does not bring the unsafe `raw` operators first, and explains better what are the existing operators and what to be careful about.
This also adds a new `through` operator, that allows for streaming handling of path matches.
This PR is a follow-up on the discussion from #666 (cc @mrdziuban)

Add safer path operators and improve documentation

---

xml/src/main/scala/fs2/data/xml/xpath/XPath.scala
xml/src/main/scala/fs2/data/xml/xpath/XPathParser.scala
xml/src/main/scala/fs2/data/xml/xpath/package.scala
xml/src/test/scala/fs2/data/xml/xpath/QueryPipeSpec.scala

Fixes #673 by building alternatives in the right order. While doing so, I discovered that the NFA generation was broken when we had alternatives, and it worked in tests because of a happy case. This PR also fixes the behavior when alternatives are involved.

Fix XPath parsing and NFA building with alternatives

---

json/circe/src/test/scala/fs2/data/json/circe/CirceJsonPathStructuredSpec.scala
json/play/src/test/scala/fs2/data/json/playJson/PlayJsonPathStructuredSpec.scala
json/src/main/scala/fs2/data/json/jsonpath/package.scala
json/src/test/scala/fs2/data/json/jsonpath/JsonPathStructuredSpec.scala
site/documentation/json/jsonpath.md
site/documentation/xml/xpath.md
xml/src/main/scala/fs2/data/xml/xpath/package.scala

This reworks the new XPath and JSONPath operators to make them more flexible:
- the operator taking a `Pipe` that emits nothing is now called `consume` to reflect its purpose more closely
- the `through` operator now takes any pipe, and will emit the output either deterministically or not depending on the `deterministic` parameter
- JSONPath now also has a `filter.deserialize[Data](jsonpath)` pipe, that allows to deserialize selected data directly.

Make path operators more flexible

---

.github/workflows/ci.yml
.sbtopts
build.sbt

Since OSSRH will be [sunset end of June](https://central.sonatype.org/news/20250326_ossrh_sunset/), let's anticipate and migrate `org.gnieh` namespace to the new central portal already.
The namespace has been migrated and the new secrets have been generated and configured at github organization level.

Publish to Central Portal instead of legacy OSSRH
