gnieh/fs2-data

build.sc
csv/src-2.12/fs2/data/csv/LiteralCellDecoders.scala
csv/src-2.13/fs2/data/csv/LiteralCellDecoders.scala
csv/src/fs2/data/csv/CellDecoder.scala
csv/test/src-2.13/fs2/data/csv/LiteralDecodersTest.scala
csv/test/src/fs2/data/csv/CellDecoderTest.scala

Plenty of standard cell decoders (including literals on 2.13), some helpful methods on `CellDecoder` itself (naming inspired by circe), simple tests.

Add more decoders for cells

---

csv/generic/src/fs2/data/csv/generic/DerivedCellDecoder.scala

fixes the problem reported on #11

Replace handleErrorWith with recoverWith to mitigate compilation failure

---

csv/generic/src/fs2/data/csv/generic/ExportMacros.scala
csv/generic/src/fs2/data/csv/generic/auto.scala
csv/generic/test/src/fs2/data/csv/generic/AutoDerivationTest.scala
csv/src/fs2/data/csv/CellDecoder.scala

For consistency as we have auto derivation for `RowDecoder` and `CsvRowDecoder` already.

Add auto derivation for CellDecoder

---

csv/src/fs2/data/csv/CellDecoder.scala
csv/src/fs2/data/csv/CellEncoder.scala
csv/src/fs2/data/csv/CsvRowDecoder.scala
csv/src/fs2/data/csv/CsvRowEncoder.scala
csv/src/fs2/data/csv/RowDecoder.scala
csv/src/fs2/data/csv/RowEncoder.scala
csv/test/src/fs2/data/csv/CellDecoderTest.scala
csv/test/src/fs2/data/csv/CellEncoderTest.scala

Inspired by #24.
Should make using the CSV type classes more beginner-friendly.

Add @implicitNotFound on CSV type classes

---

csv/src/fs2/data/csv/internals/RowParser.scala
csv/test/src/fs2/data/csv/CsvExceptionSpec.scala

This ports to CSV what was done for JSON and XML.

Emit CSV rows before raising

---

.travis.yml
build.sc
csv/src/fs2/data/csv/internals/RowParser.scala
csv/src/fs2/data/csv/internals/RowWriter.scala
json/src/fs2/data/json/SelectorParser.scala
json/src/fs2/data/json/internal/TokenParser.scala
json/src/fs2/data/json/internal/ValueParser.scala
xml/src/fs2/data/xml/internals/EventParser.scala
xml/src/fs2/data/xml/internals/Normalizer.scala
xml/src/fs2/data/xml/internals/ReferenceResolver.scala

This PR upgrade scala to 2.13.3 with small changes to avoid warnings added in 2.13.3

Upgrade scala version to 2.13.3

---

build.sbt

Let's wait until weaver is release (or at least a milestone) with final CE3 and fs2 3 versions.

Update to fs2 version 3

---

csv/shared/src/main/scala/fs2/data/csv/RowF.scala

Prepares for changes in overload resolution in Scala 3(-RC2) which make these overloaded methods very annoying to implement and hard to call. Even though we have no Scala 3 support yet, it avoids a breaking change or Scala version-dependent API difference in fs2-data's 1.0.

Rename overloads in RowF

---

README.md
csv/jvm/src/test/scala/fs2/data/csv/CsvParserTest.scala
csv/shared/src/main/scala/fs2/data/csv/RowDecoderF.scala
csv/shared/src/main/scala/fs2/data/csv/RowEncoderF.scala
csv/shared/src/main/scala/fs2/data/csv/package.scala
documentation/docs/csv/generic.md
documentation/docs/csv/index.md

New pipes are there as planned, lacks docs and tests. More description to follow. 
Closes #44

New CSV pipes

---

xml/shared/src/main/scala/fs2/data/xml/internals/EventParser.scala

Rewrites all for-comprehensions that require bm4 to to compile into explicit flatMap chains. That helps transitioning to Scala 3 where there is (so far) no support for extracting tuples in for-comprehensions. Not removing bm4 from the build as Scala 2 will still profit from tail-map elimination in the remaining for-comprehensions.
Rewrite was done using IDEA, probably one could manually make some of the `flatMap` stacks nicer (I already optimised formatting though).

Drop need for better-monadic-for

---

csv/shared/src/main/scala/fs2/data/csv/RowF.scala

Having it as a def allowed for statically checking that headers are
defined and avoid accidental call to it when no headers are defined.
However, this implies that the map is recomputed for each access to a
function like `as`, which induces significant overhead.
Turning it into a lazy has these implications:
- significantly improve performance when transforming rows with lots of
cells
- calling this field becomes more unsafe since there is no static check
anymore that the headers are actually defined
However the risk is mitigated by the fact that this private field is
called by a quite stable API which has the constraint, ensuring the call
is safe and by adding a deprecation warning so that new uses will at
least be made aware of having to check things.
Fixes #205

Cache the `byHeader` field

---

build.sbt
documentation/docs/json/libraries.md
json/circe/shared/src/main/scala/fs2/data/json/circe/package.scala
json/play/shared/src/main/scala/fs2/data/json/playJson/package.scala
json/play/shared/src/test/scala/fs2/data/json/playJson/JsonExceptionSpec.scala
json/play/shared/src/test/scala/fs2/data/json/playJson/JsonMergePatchTest.scala
json/play/shared/src/test/scala/fs2/data/json/playJson/JsonSelectorSpec.scala
json/play/shared/src/test/scala/fs2/data/json/playJson/TokenizerSpec.scala

Add support for Play! JSON

---

csv/shared/src/main/scala/fs2/data/csv/CsvRow.scala
csv/shared/src/test/scala/fs2/data/csv/LineNumberPreservationTest.scala

Retain line numbers when constructing CsvRow

---

.github/workflows/ci.yml
build.sbt
cbor-json/shared/src/main/scala/fs2/data/cbor/package.scala
cbor-json/shared/src/main/scala/fs2/data/json/package.scala
cbor-json/shared/src/test/resources/appendix_a.json
cbor-json/shared/src/test/scala/fs2/data/cbor/AppendixTestCase.scala
cbor-json/shared/src/test/scala/fs2/data/cbor/CborToJsonSpec.scala
cbor-json/shared/src/test/scala/fs2/data/cbor/JsonToCborSpec.scala
cbor/shared/src/main/scala/fs2/data/cbor/Diagnostic.scala
cbor/shared/src/main/scala/fs2/data/cbor/HalfFloat.scala
cbor/shared/src/main/scala/fs2/data/cbor/Tags.scala
cbor/shared/src/main/scala/fs2/data/cbor/low/internal/ItemParser.scala
cbor/shared/src/main/scala/fs2/data/cbor/package.scala
cbor/shared/src/test/resources/appendix_a.json
cbor/shared/src/test/scala/fs2/data/cbor/AppendixTestCase.scala
cbor/shared/src/test/scala/fs2/data/cbor/ParserSpec.scala
documentation/docs/cbor-json/index.md
site/content/index.md

Add CBOR/JSON interoperability

---

finite-state/shared/src/main/scala/fs2/data/pfsa/TreeQueryPipe.scala
json/src/main/scala/fs2/data/json/jsonpath/package.scala
json/src/test/scala/fs2/data/json/jsonpath/JsonPathSpec.scala
xml/src/main/scala/fs2/data/xml/xpath/package.scala

By allowing to configure maximum match nesting level and maximum match
count, we can avoid opening unnecessary matching streams, reducing the
memory footprint. This is particularly interesting for operator such as
`first` or to get only top-most matches in case of recursive queries.

Make matching behavior configurable

---

finite-state/shared/src/main/scala/fs2/data/esp/ESP.scala
finite-state/shared/src/main/scala/fs2/data/esp/Rhs.scala
finite-state/shared/src/main/scala/fs2/data/mft/MFT.scala
finite-state/shared/src/main/scala/fs2/data/mft/MFTBuilder.scala
finite-state/shared/src/main/scala/fs2/data/mft/package.scala
finite-state/shared/src/main/scala/fs2/data/pattern/Compiler.scala
finite-state/shared/src/test/scala/fs2/data/esp/CopySpec.scala
finite-state/shared/src/test/scala/fs2/data/esp/DupSpec.scala
finite-state/shared/src/test/scala/fs2/data/esp/ESPSpec.scala

This adds a new possiblity in addition to the ability to call on
children and siblings, by allowing more powerful transformations applied
to the root itself.

Add possibility to call transformation on self

---

documentation/docs/csv/index.md

Better late than never :D.
I'm not sure if I put the clarification in the right place, open to any kind of feedback.

Add clarification for separator in high level API

---

finite-state/shared/src/main/scala/fs2/data/mft/MFT.scala
finite-state/shared/src/main/scala/fs2/data/mft/MFTBuilder.scala
finite-state/shared/src/main/scala/fs2/data/mft/package.scala
finite-state/shared/src/test/scala/fs2/data/esp/ESPSpec.scala
finite-state/shared/src/test/scala/fs2/data/pattern/example/ArticleSpec.scala

The new DSL allows for a one step check of pattern and guard.

Improve MFT guard power

---

README.md

Add a badge as described in https://github.com/typelevel/governance/issues/72.

Add typelevel badge

---

json/src/main/scala/fs2/data/json/internal/JsonTokenParser.scala
json/src/test/scala/fs2/data/json/Issue515Spec.scala

Fix output duplication on escaped chunk boundaries

---

site/index.md

This first list is generated by finding direct dependents in Maven Central Repository.

Add adopters

---

site/index.md

Proud fs2-data users over here :)

Add Mobimeo as adopter

---

xml/src/main/scala/fs2/data/xml/xpath/XPath.scala
xml/src/main/scala/fs2/data/xml/xpath/XPathParser.scala
xml/src/main/scala/fs2/data/xml/xpath/package.scala
xml/src/test/scala/fs2/data/xml/xpath/QueryPipeSpec.scala

Port XPath atlernative fixes to main

---

build.sbt

I migrated my account to piaille.

Update link to mastodon account
